server:
  port: 8080

google:
  drive:
    credentials-path: credentials/team-challenge-chat-470408-f0287fce68a3.json
    application-name: "Avatar Service"
    folder-id: 1B9ZI9IZebmtFzrREXJbSylmwTypdrEmR

jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400 # 24 hours in seconds
  refresh-expiration: 2592000 # 30 days in seconds
  test-expiration: 60 # 1 minute for tests

springdoc:
  api-docs:
    path: /q/api-docs
  swagger-ui:
    path: /q/swagger-ui
  packages-to-scan: com.example.chatapp

springwolf:
  enabled: true
  docket:
    base-package: com.example.chatapp
    info:
      title: WebSocket Chat API
      version: 1.0.0
      description: AsyncAPI documentation for WebSocket-based chat application
    servers:
      stomp-server:
        protocol: stomp
        host: localhost:8080
  ui:
    defaults:
      show-bindings: true
      show-headers: true

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB


app:
  mail:
    from: chat.app@chat.com
    from-name: Chat App

logging:
  level:
    com.yourpackage: DEBUG
    com.google.api: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"